# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether the user             can log into this admin site.', verbose_name='staff status'),
        ),
    ]
