# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=users.models.get_image_path),
            preserve_default=False,
        ),
    ]
