# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180605_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='blank.png', upload_to='profile_image'),
        ),
    ]
