# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=30)),
                ('propic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.AlbumImage')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='people',
            field=models.ManyToManyField(to='albums.People'),
        ),
    ]
