# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20180711_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.PROTECT, to='albums.Album'),
        ),
    ]
