# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20180711_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='height',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='width',
            field=models.IntegerField(default=None),
        ),
    ]
