# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20180711_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='people',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
