# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20180711_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='remind_on',
        ),
        migrations.AddField(
            model_name='people',
            name='remind_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
