# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20180711_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='event',
            field=models.TextField(default='No Event'),
        ),
    ]
