# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_people_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='associated_with',
            field=models.ManyToManyField(to='albums.AlbumImage'),
        ),
        migrations.AlterField(
            model_name='people',
            name='propic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_pic', to='albums.AlbumImage'),
        ),
    ]
