# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20180711_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='width',
        ),
    ]
