# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_people_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='favourite',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='albums.AlbumImage'),
            preserve_default=False,
        ),
    ]
